version: '3'

services:
  app:
    build:
      context: .
    ports:
      - 5001:5001
    volumes:
      - .:/app
    environment:
      FLASK_APP: app/__init__.py
      FLASK_ENV: development
      MYSQL_HOST: db
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
      REDIS_URL: "redis://cache:6379/0"
    depends_on:
      - db
      - cache

  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
    ports:
      - '3306:3306'
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d

  cache:
    image: redis:6.2.5
    ports:
      - '6379:6379'
